In [1]:
import numpy as np

In [2]:
arr_1=[n**2 for n in range(20)]
arr_n1=np.array(arr_1)
arr_n1.shape

(20,)

In [3]:
arr_2=[[1,2,3],['a','b','c']]
arr_n2=np.array(arr_2)
arr_n2

array([['1', '2', '3'],
       ['a', 'b', 'c']], dtype='<U11')

## Built-in Methods

### arange

Return evenly spaced values within a given interval.

In [11]:
arr_n3=np.arange(10)
arr_n3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr_n4=np.arange(10,20)
arr_n4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
arr_n4=np.arange(20,30,3)
arr_n4

array([20, 23, 26, 29])

### zeros and ones

Generate arrays of zeros or ones

In [16]:
arr_ones=np.ones(10)
arr_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
arr_zs=np.zeros(12)
arr_zs

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
arr_ones_1=np.ones((10,5))
arr_ones_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
arr_zeros_1=np.zeros((5,4))
arr_zeros_1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [22]:
arr_lin=np.linspace(10,20,5)
arr_lin

array([10. , 12.5, 15. , 17.5, 20. ])

## eye

Creates an identity matrix

In [28]:
arr_eye=np.eye(10,10)
arr_eye

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [58]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [31]:
arr_rand=np.random.rand(3,4)
arr_rand

array([[0.38647235, 0.22468138, 0.75161751, 0.88217697],
       [0.69914076, 0.26091721, 0.33003804, 0.85113176],
       [0.86912512, 0.0032653 , 0.2893924 , 0.5139424 ]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [32]:
arr_randn=np.random.randn(4,5)
arr_randn

array([[ 0.47568052,  0.10298436, -0.17515821,  0.16490744, -0.19648154],
       [ 2.0938907 ,  0.16220848, -1.0594364 ,  0.31976793,  0.0512854 ],
       [-0.3073054 ,  0.90698129,  1.78740777,  0.16236166,  1.59846768],
       [-0.43658619,  0.25185525, -0.49804867, -0.98643118, -0.96735663]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [34]:
np_randint=np.random.randint(1,4)
np_randint

3

In [35]:
np_randint=np.random.randint(1,4,(2,3))
np_randint

array([[3, 1, 3],
       [3, 1, 3]])

In [37]:
np_randint=np.random.randint(1,20,5)
np_randint

array([18,  3, 13, 15, 14])

#

In [16]:
arr=np.arange(50)
ranarr=np.random.randint(10,30,10)

## Reshape
Returns an array containing the same data with a new shape.

In [41]:
arr_resh=arr.reshape(5,10)
arr_resh

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [43]:
max=arr.max()
max

49

In [46]:
ranarr

array([18, 20, 22, 28, 26, 27, 20, 15, 27, 19])

In [44]:
min=ranarr.min()
min

15

In [49]:
max_p=ranarr.argmax()
max_p

3

In [50]:
min_p=arr.argmin()
min_p

0

## Shape

Shape is an attribute that arrays have (not a method):

In [52]:
arr_shape=arr.shape
arr_shape

(50,)

In [53]:
arr.reshape(5,10).shape

(5, 10)

### dtype

You can also grab the data type of the object in the array:

In [58]:
arr.dtype

dtype('int32')

##

In [60]:
arr_n5=np.arange(50)
arr_n5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [61]:
arr_n5[5]

5

In [62]:
arr_n5[1:5]

array([1, 2, 3, 4])

In [63]:
arr_n5[1:10:2]

array([1, 3, 5, 7, 9])

In [64]:
arr_n5[:10:-2]

array([49, 47, 45, 43, 41, 39, 37, 35, 33, 31, 29, 27, 25, 23, 21, 19, 17,
       15, 13, 11])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [65]:
arr_1=np.arange(20)
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [68]:
slice_1=arr_1[5:10]
slice_1

array([5, 6, 7, 8, 9])

In [69]:
slice_1[:]=55
slice_1

array([55, 55, 55, 55, 55])

In [70]:
arr_1

array([ 0,  1,  2,  3,  4, 55, 55, 55, 55, 55, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [72]:
arr_copy=arr_1[5:10].copy()
arr_copy

array([55, 55, 55, 55, 55])

## Indexing a 2D array (matrices)

**arr_2d[row][col]** or **arr_2d[row,col]**

In [73]:
arr_2d=np.arange(25).reshape(5,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [74]:
arr_2d[2]

array([10, 11, 12, 13, 14])

In [75]:
arr_2d[2,3]

13

In [76]:
arr_2d[:,3]

array([ 3,  8, 13, 18, 23])

In [78]:
arr_2d[1:3,2:4]

array([[ 7,  8],
       [12, 13]])

Selection based off of comparison operators.

In [79]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [80]:
arr_comp1=arr[arr%2==0].copy()
arr_comp1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [81]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [84]:
arr_2d_1=arr_2d[arr_2d>7].copy()
arr_2d_1

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

## Arithmetic

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [87]:
arr_sum=arr+arr
arr_sum

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [88]:
arr_prod=arr*arr
arr_prod

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401])

# Universal functions

In [91]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ])

In [92]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
       -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388,
       -0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
       -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539,
        0.74511316, -0.15862267, -0.91652155, -0.83177474,  0.01770193,
        0.85090352,  0.90178835,  0.12357312, -0.76825466, -0.95375265])

In [18]:
np.sum(arr)

1225

In [20]:
arr_2d=np.arange(20).reshape(5,4)
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [21]:
np.sum(arr_2d,axis=1)

array([ 6, 22, 38, 54, 70])

In [22]:
np.sum(arr_2d,axis=0)

array([40, 45, 50, 55])

In [93]:
np.max(arr)

49

In [94]:
np.argmax(arr)

49

In [4]:
arr_1=np.arange(10,30,2)
arr_1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [5]:
arr_1.fill(1)
arr_1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Convert Data Types

In [8]:
arr_2=np.array([1,2,3,4],dtype=np.float32)
arr_2

array([1., 2., 3., 4.], dtype=float32)

In [13]:
arr_33=np.asarray(arr_2,dtype=np.object)
arr_33

array([1.0, 2.0, 3.0, 4.0], dtype=object)

# Misc

In [23]:
arr_1=np.array([1,2,3,4,5,6,7])
arr_1.clip(3,5)

array([3, 3, 3, 4, 5, 5, 5])

In [24]:
arr_1_2d=np.arange(20).reshape(5,4)
arr_1_2d.clip(5,7)

array([[5, 5, 5, 5],
       [5, 5, 6, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [54]:
arr_n1=np.linspace(-10,10,5)
arr_n2=np.linspace(-10,10,5)
x,y=np.meshgrid(arr_n1,arr_n2)
x

array([[-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.]])

In [55]:
y

array([[-10., -10., -10., -10., -10.],
       [ -5.,  -5.,  -5.,  -5.,  -5.],
       [  0.,   0.,   0.,   0.,   0.],
       [  5.,   5.,   5.,   5.,   5.],
       [ 10.,  10.,  10.,  10.,  10.]])

In [56]:
arr_1=np.array([1,2,3,4,5])
np.zeros_like(arr_1)

array([0, 0, 0, 0, 0])

In [57]:
np.ones_like(arr_1)

array([1, 1, 1, 1, 1])

# Sorting

In [29]:
arr_s=np.arange(30).reshape(5,6)[::-1]
arr_s

array([[24, 25, 26, 27, 28, 29],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [33]:
np.sort(arr_s)

array([[24, 25, 26, 27, 28, 29],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

# Get indices where to insert

In [34]:
arr_2=np.arange(10)
arr_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr_3=np.array([3.5,5.5,7.2])
np.searchsorted(arr_2,arr_3)

array([4, 6, 8], dtype=int64)

# Transpose

In [37]:
arr_5=np.arange(30).reshape(5,6)
arr_5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [38]:
arr_5.transpose()

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

# Concatenate

In [40]:
arr_6=np.arange(9).reshape(3,3)
arr_6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
arr_7=np.arange(6).reshape(2,3)
arr_7

array([[0, 1, 2],
       [3, 4, 5]])

In [45]:
arr_conc=np.concatenate((arr_6,arr_7))
arr_conc

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

In [48]:
np.vstack((arr_6,arr_7))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

In [50]:
np.hstack((arr_6,arr_6))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [51]:
arr_7.flatten()

array([0, 1, 2, 3, 4, 5])

In [52]:
arr_6.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# Logical Operations

In [60]:
arr_1=np.arange(10,20)
arr_2=np.arange(15,25)
arr_1==arr_2

array([False, False, False, False, False, False, False, False, False,
       False])

# Shuffle

In [61]:
arr_2=np.arange(30).reshape(5,6)
arr_2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [63]:
np.random.shuffle(arr_2)
arr_2

array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

## Reading Files

In [5]:
%%writefile test_file.txt
1 2 3 4
5 6 7 8
9 10 11 12

Overwriting test_file.txt


In [6]:
arr_f=np.loadtxt('test_file.txt')
arr_f

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [7]:
%%writefile test_file1.txt
1,2,3,4
5,6,7,8

Writing test_file1.txt


In [8]:
arr_f1=np.loadtxt('test_file1.txt',delimiter=',')
arr_f1

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [9]:
%%writefile test_file2.txt
abc
1,2,3,4
5,6,7,8

Writing test_file2.txt


In [11]:
arr_f3=np.loadtxt('test_file2.txt',delimiter=',',skiprows=1)
arr_f3

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

## Writing Files

In [12]:
arr_w=np.arange(20).reshape(5,4)
arr_w

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [13]:
np.random.shuffle(arr_w)
arr_w

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [15]:
np.savetxt('test_write.txt',arr_w,fmt='%d')

In [16]:
arr_w1=np.array([1,2,3,4,5])
np.save('test_1.npy',arr_w1)

In [19]:
arr_w2=np.load('test_1.npy')
arr_w2

array([1, 2, 3, 4, 5])

In [21]:
arr_w3=np.arange(100)
np.savez('test_z.npz',a=arr_w1,b=arr_w3)

In [22]:
w_dict=np.load('test_z.npz')

In [24]:
w_dict['a']

array([1, 2, 3, 4, 5])

In [27]:
w_dict['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])